remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: Pulse
description: "PUshing Low-carbon Services towards the Edge"
source: docs

#baseurl: "/defi-pulse"
url: "https://defi-pulse.github.io/"
