theme: minima

title: PULSE
description: "PUshing Low-carbon Services towards the Edge"

url: "https://defi-pulse.github.io/"

author:
  name: Copyright © 2024 Inria

header_pages:
  - index.md
  - consortium.md
  - news.md
  - publications.md
